// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3SNAsWnMaO-lwDIf11J50aHuPbYg-nMw',
    appId: '1:864521237115:web:7a9c1d5f3d65b699c3e8de',
    messagingSenderId: '864521237115',
    projectId: 'mobile-c6837',
    authDomain: 'mobile-c6837.firebaseapp.com',
    storageBucket: 'mobile-c6837.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBua00537nHNnBZPlxWP0H18DW1K6Wwa0Y',
    appId: '1:864521237115:android:42b18716cf8d87e8c3e8de',
    messagingSenderId: '864521237115',
    projectId: 'mobile-c6837',
    storageBucket: 'mobile-c6837.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZifnzVEAHo6nV7wZQuwvLwrklLymi_z8',
    appId: '1:864521237115:ios:1ea7e76736ee4a74c3e8de',
    messagingSenderId: '864521237115',
    projectId: 'mobile-c6837',
    storageBucket: 'mobile-c6837.firebasestorage.app',
    iosBundleId: 'com.example.fundmateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZifnzVEAHo6nV7wZQuwvLwrklLymi_z8',
    appId: '1:864521237115:ios:1ea7e76736ee4a74c3e8de',
    messagingSenderId: '864521237115',
    projectId: 'mobile-c6837',
    storageBucket: 'mobile-c6837.firebasestorage.app',
    iosBundleId: 'com.example.fundmateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3SNAsWnMaO-lwDIf11J50aHuPbYg-nMw',
    appId: '1:864521237115:web:1de3f9b330acf208c3e8de',
    messagingSenderId: '864521237115',
    projectId: 'mobile-c6837',
    authDomain: 'mobile-c6837.firebaseapp.com',
    storageBucket: 'mobile-c6837.firebasestorage.app',
  );
}
